[build]
command = "node_modules/.bin/tsc -p tsconfig.build.json && vite build --config ./vite.config.ts"
publish = "dist"

[build.environment]
NODE_ENV = "production"

[build.image]
name = "node"
version = "20"

[cache]
directories = ["node_modules", ".npm"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
