[build]
  command = "npm install && npx tsc && npm run build"
  publish = "dist"
  base = "src"

[build.image]
name = "node"
version = "20"

[cache]
directories = ["node_modules"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
NODE_ENV = "production"

[context.production]
deploy_to = "wealthaegis"
